---
title: "Task 3 - Santa Barbara Urchins (Gracer)"
author: "Allison Gracer"
date: "10/25/2021"
output: 
  html_document: 
    theme: spacelab
---

## Overview

**Data Citation:** Reed, D. 2020. SBC LTER: Reef: Long-term experiment: Kelp removal: Urchin size frequency distribution ver 20. Environmental Data Initiative. https://doi.org/10.6073/pasta/5a1e9ef03aa47bd2225c0bb98a02a63b. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
library(tidyverse)
library(here)
```

## Setup

```{r}
# Attach packages
library(tidyverse)
library(here)
```

## Read in the data

```{r}
urchins <- read_csv(here("data", "urchins.csv")) %>% 
clean_names()
```

## Data visualization

```{r}
ggplot(data = urchins, aes(x = size)) +
  geom_histogram(fill = "sienna3",
                 color = "sienna4",
                 bins = 10) +
  facet_wrap(~ common_name) +
  scale_x_continuous(limits = c(0, 14)) +
  labs(x = "Urchin Diameter (cm)",
       y = "Count of Urchins in Sample",
       title = "Purple and Red Urchin Size(cm)") +
  theme(plot.title = element_text(hjust = 0.5))

```

